package com.edat.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AutorizadoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutorizadoAllPropertiesEquals(Autorizado expected, Autorizado actual) {
        assertAutorizadoAutoGeneratedPropertiesEquals(expected, actual);
        assertAutorizadoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutorizadoAllUpdatablePropertiesEquals(Autorizado expected, Autorizado actual) {
        assertAutorizadoUpdatableFieldsEquals(expected, actual);
        assertAutorizadoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutorizadoAutoGeneratedPropertiesEquals(Autorizado expected, Autorizado actual) {
        assertThat(expected)
            .as("Verify Autorizado auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutorizadoUpdatableFieldsEquals(Autorizado expected, Autorizado actual) {
        assertThat(expected)
            .as("Verify Autorizado relevant properties")
            .satisfies(e -> assertThat(e.getNombre()).as("check nombre").isEqualTo(actual.getNombre()))
            .satisfies(e -> assertThat(e.getApellido()).as("check apellido").isEqualTo(actual.getApellido()))
            .satisfies(e -> assertThat(e.getDni()).as("check dni").isEqualTo(actual.getDni()))
            .satisfies(e -> assertThat(e.getTelefono()).as("check telefono").isEqualTo(actual.getTelefono()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAutorizadoUpdatableRelationshipsEquals(Autorizado expected, Autorizado actual) {
        assertThat(expected)
            .as("Verify Autorizado relationships")
            .satisfies(e -> assertThat(e.getAlumnos()).as("check alumnos").isEqualTo(actual.getAlumnos()));
    }
}
